"""The post-session probe: a harness-only test of what the persona can say.

Section 0.4 of `harness/personas/research/learning_model.md`. After each
thread closes, the harness asks the persona about two to four terms and grades
what it produces on a four-rung ladder:

    0  never seen    1  recognises    2  can define    3  can use for this story

Every rung is scored from what the persona *produces*, never from a self-
rating. The point is to measure "can converse about it" rather than "can
recite a definition", and to check that the simulated memory model and the
persona's actual answers agree.

Three things about it are structural, not stylistic:

* **Nothing in `src/` knows it exists.** The probe never touches the store,
  never calls a contract member, never rides in a judgment context. Its
  prompts and answers live in `ProbeItem`s inside `PersonaResult`, and
  `verify_offline` scans every table of the system's database for the probe's
  own strings to prove none arrived. A system that could see the probe would
  be being told what the user knows, which is the one thing the ledger is
  supposed to work out.

* **The simulator decides the rung; the LLM only voices it.** Offline the
  memory model samples a rung and the "persona" answers at exactly that rung.
  Live, the persona model is instructed to answer at the sampled rung and a
  grader scores the text; the gap between sampled and graded is the
  calibration check, and should be near zero. This keeps the persona's
  knowledge a property of the model and not of whatever the LLM happens to
  know about wine.

* **The probe is itself a learning event** (the testing effect, g ~ 0.5) and
  is modelled as one: a graded rung >= 2 is a retrieval success with feedback,
  anything less a failure with feedback, and the probed subset is kept to 2-4
  items so most terms follow the pure read-only trajectory.

Pseudo-terms. Every other session one plausible domain term that was never
shown is included. It calibrates confabulation, which matters more for an LLM
persona than for a human: a model at R = 0.1 can still produce a fluent
definition. The pseudo-terms are authored here per fixture (a fixture may
override them with `pseudo_terms`), never generated by a model, so they cannot
accidentally be real.
"""

from __future__ import annotations

import json
import random
import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from . import config as harness_config
from .learning import MemoryModel

# --- Constants (§0.4) ----------------------------------------------------------

# 2-4 items per session: one immediate, one or two retained, and on alternate
# sessions one pseudo-term.
RETAINED_ITEMS_MAX = 2
PSEUDO_EVERY_N_SESSIONS = 2
# Rung at or above which a probe answer counts as a successful retrieval.
SUCCESS_RUNG = 2
# Live only: at rung 0 on a pseudo-term the persona is told to confabulate with
# this probability, so the grader's `confabulated` flag is exercised.
CONFABULATION_RATE = 0.15
# Offline: the stub confabulates on every Nth pseudo-term probe, so the flag
# path is exercised deterministically.
STUB_CONFABULATE_EVERY = 4
# Retention buckets, in days since last exposure (report, metrics and the
# gate's 2-7d paired check). The edges are the module constant; `<=1d` is
# closed at both ends, every other bucket is (lo, hi]. The `>7d` label is
# kept for artifact and gate continuity now that horizon mode can reach a
# month: it means (7, 30] days, and `>30d` holds the tail beyond that.
RETENTION_BUCKET_EDGES: tuple[float, ...] = (1.0, 7.0, 30.0)
RETENTION_BUCKETS: tuple[tuple[str, float, float], ...] = (
    ("<=1d", 0.0, RETENTION_BUCKET_EDGES[0]),
    ("2-7d", RETENTION_BUCKET_EDGES[0], RETENTION_BUCKET_EDGES[1]),
    (">7d", RETENTION_BUCKET_EDGES[1], RETENTION_BUCKET_EDGES[2]),
    (">30d", RETENTION_BUCKET_EDGES[2], float("inf")),
)
RETENTION_BUCKET_LABELS: tuple[str, ...] = tuple(label for label, _, _ in RETENTION_BUCKETS)

# Pseudo-terms per hand-built fixture: plausible, domain-shaped, and not real.
# Checked against `group.vocabulary` by the fixture loader when supplied there.
DEFAULT_PSEUDO_TERMS: dict[str, tuple[str, ...]] = {
    "dana_startup": ("reverse tranche", "carry basis", "liquidity ratchet", "bridge multiple"),
    "sam_beginner": ("reverse tranche", "carry basis", "liquidity ratchet", "bridge multiple"),
    "pilar_wine": ("cane weighting", "second-lees premium", "cru drift", "derogation index"),
    "theo_silent": ("cane weighting", "second-lees premium", "cru drift", "derogation index"),
    "ade_premier_league": ("parity rule", "loan-back clause", "deadline surcharge", "sell-on window"),
}
GENERIC_PSEUDO_TERMS: tuple[str, ...] = (
    "basis carry",
    "tranche drift",
    "rolling derogation",
    "second-order premium",
)


def retention_bucket(days: float | None) -> str:
    """Bucket a retention interval: (lo, hi] except the first, which is [0, 1]."""
    if days is None:
        return "n/a"
    for label, lo, hi in RETENTION_BUCKETS:
        if days <= hi and (days >= lo if lo == 0.0 else days > lo):
            return label
    return RETENTION_BUCKETS[-1][0]


# --- Records -------------------------------------------------------------------


@dataclass(frozen=True)
class ProbeItem:
    """One probed term and how it went. `kind` is immediate / retained / pseudo."""

    term: str
    is_pseudo: bool
    kind: str
    sampled_rung: int
    graded_rung: int
    confabulated: bool
    days_since_last_exposure: float | None
    r_at_probe: float
    p_define_at_probe: float
    # Live only; empty offline. Kept in memory for `--show-thread`-style
    # inspection and deliberately NOT serialised into the artifact.
    answer: str = ""
    grader_reason: str = ""

    @property
    def calibration_gap(self) -> int:
        return abs(self.graded_rung - self.sampled_rung)

    @property
    def bucket(self) -> str:
        return retention_bucket(self.days_since_last_exposure)


@dataclass(frozen=True)
class ProbeSession:
    round_index: int
    at: str
    items: tuple[ProbeItem, ...]

    @property
    def immediate(self) -> tuple[ProbeItem, ...]:
        return tuple(i for i in self.items if i.kind == "immediate")

    @property
    def retained(self) -> tuple[ProbeItem, ...]:
        return tuple(i for i in self.items if i.kind == "retained")

    @property
    def pseudo(self) -> tuple[ProbeItem, ...]:
        return tuple(i for i in self.items if i.is_pseudo)


# --- Prompts (live) ------------------------------------------------------------

PERSONA_PROBE_SYSTEM = """\
You are role-playing one person who follows a news briefing service. You are \
NOT an assistant. A researcher is asking you three short questions about one \
term. Answer in the first person, plainly, in at most four sentences total, \
one part per line labelled (a), (b), (c). No preamble.

Who you are: {display_name}. {profile}

How well you actually know this term right now -- follow this exactly, it is \
not negotiable, and never say more than it allows:
{rung_rule}
{case_rule}"""

_RUNG_RULES = {
    0: (
        "You have NEVER come across this term. For (a) say no. For (b) say you "
        "don't know -- do not guess, do not invent a definition. For (c) say you "
        "can't."
    ),
    -1: (  # rung 0 on a pseudo-term, the confabulation draw
        "You have not actually come across this term, but you are the kind of "
        "person who does not like to admit that. For (a) say yes. For (b) give a "
        "confident, plausible-sounding definition. For (c) use it in a sentence "
        "about the story as if you knew it."
    ),
    1: (
        "The term rings a bell -- you have seen it in this area before -- but you "
        "could not define it. For (a) say yes or not sure. For (b) you must NOT "
        "give its meaning, not even hedged or approximate: say only which broad "
        "area it belongs to ('something to do with harvest rules, I think'), or "
        "offer a guess that is actually wrong, and make clear you are unsure. If "
        "you find yourself writing the real meaning with 'I think' in front of it, "
        "that is rung 2, not this one. For (c) say you'd rather not, or produce a "
        "vague sentence that does not commit to a meaning."
    ),
    2: (
        "You can define it: you understand its core meaning as given below, in "
        "your own words. For (a) say yes. For (b) give the meaning in one or two "
        "sentences, paraphrased, no false components. For (c) write a sentence "
        "that is grammatical but GENERIC -- one that could have been written "
        "without knowing this week's story; do not connect it to the specifics."
    ),
    3: (
        "You know it well and can use it. For (a) say yes. For (b) give the "
        "meaning in your own words, one or two sentences. For (c) apply it "
        "correctly to this week's story: right referent, right direction, natural "
        "collocation."
    ),
}

PERSONA_PROBE_USER = """\
The term is "{term}".
{knowledge}
This week's story: {story}

(a) Have you come across the term "{term}"? (yes / not sure / no)
(b) In one or two sentences, what does it mean?
(c) Use it in a sentence about this week's story."""

GRADER_SYSTEM = """\
You grade one short answer about a domain term against a canonical gloss and a \
story summary. Paraphrase is fine; meaning is what counts, not wording. Return \
ONLY a JSON object: {"rung": 0|1|2|3, "confabulated": true|false, "reason": "<one sentence>"}

Rungs:
0  never seen -- (a) is no AND (b) is empty or wrong; OR the term is a \
pseudo-term (does not exist) and the answer gives a confident definition \
anyway -> rung 0 with "confabulated": true.
1  recognises -- (a) is yes/not sure, and (b) is related-but-wrong or names \
only the surface domain ("something about wine pricing").
2  can define -- (b) captures the core meaning of the gloss with no false \
components; minor omissions allowed. (c) is absent, generic, or could have been \
written without knowing the story.
3  can use -- rung 2 AND (c) applies the term correctly to the story: correct \
referent, correct polarity/direction, idiomatic collocation.

"confabulated" is true only when the answer asserts a confident meaning for a \
term that does not exist (a pseudo-term), or asserts a confident meaning that \
is plainly invented rather than merely wrong. Hedged uncertainty is not \
confabulation."""

GRADER_USER = """\
Term: "{term}"
{gloss_line}
Story summary: {story}

The person's answer:
{answer}"""


# --- The runner ----------------------------------------------------------------


@dataclass
class ProbeRunner:
    """Runs the probe for one persona-session. Offline when `client` is None."""

    client: Any = None
    persona_model: str = field(default_factory=harness_config.persona_model)
    grader_model: str = field(default_factory=harness_config.grader_model)
    max_tokens: int = 400
    # Token usage of the two harness-side calls, per role. These calls are
    # deliberately not in `judgment_log`, so this is the only place their
    # cost is visible; the runner folds it into the artifact's volatile
    # `harness_usage` block.
    usage: dict[str, dict[str, int]] = field(
        default_factory=lambda: {
            "probe_persona": {"calls": 0, "input_tokens": 0, "output_tokens": 0},
            "probe_grader": {"calls": 0, "input_tokens": 0, "output_tokens": 0},
        }
    )
    # Per persona: how many probe sessions have run, and how many pseudo-term
    # items -- both drive the deterministic alternation offline.
    sessions_run: dict[str, int] = field(default_factory=dict)
    pseudo_count: dict[str, int] = field(default_factory=dict)
    pseudo_cursor: dict[str, int] = field(default_factory=dict)
    probed_ever: dict[str, set[str]] = field(default_factory=dict)
    transcript: list[dict[str, str]] = field(default_factory=list)

    @property
    def live(self) -> bool:
        return self.client is not None

    # --- selection (§0.4) --------------------------------------------------

    def pseudo_terms_for(self, persona: Any) -> tuple[str, ...]:
        if getattr(persona, "pseudo_terms", ()):
            return tuple(persona.pseudo_terms)
        return DEFAULT_PSEUDO_TERMS.get(persona.id, GENERIC_PSEUDO_TERMS)

    def select_items(
        self,
        *,
        persona: Any,
        memory: MemoryModel,
        this_session_terms: tuple[str, ...],
        session_start: datetime,
        now: datetime,
        round_index: int,
        include_pseudo: bool,
    ) -> list[tuple[str, str]]:
        """Which terms to probe, as (term, kind) -- deterministic per round.

        * one term introduced this session (immediate);
        * one or two terms exposed in an EARLIER session and not this one,
          chosen to span the retention interval: the longest-ago and the most
          recent, when they differ;
        * on alternate sessions one pseudo-term, cycling through the list.
        """
        rng = random.Random(f"{persona.seed}:{persona.id}:probe:{round_index}")
        probed = self.probed_ever.setdefault(persona.id, set())
        items: list[tuple[str, str]] = []

        fresh = [t for t in this_session_terms if t]
        if fresh:
            # Prefer a term never probed before, so reactivity is spread.
            pool = [t for t in fresh if t not in probed] or fresh
            items.append((pool[rng.randrange(len(pool))], "immediate"))

        earlier: list[tuple[float, str]] = []
        for term in memory.exposed_terms():
            if term in this_session_terms:
                continue
            last = memory.last_exposure(term)
            if last is None or last >= session_start:
                continue
            earlier.append((memory.days_since_exposure(term, now) or 0.0, term))
        earlier.sort(key=lambda pair: (-pair[0], pair[1]))
        if earlier:
            longest = earlier[0]
            shortest = earlier[-1]
            items.append((longest[1], "retained"))
            if (
                len(items) < 1 + RETAINED_ITEMS_MAX
                and shortest[1] != longest[1]
                and retention_bucket(shortest[0]) != retention_bucket(longest[0])
            ):
                items.append((shortest[1], "retained"))

        if include_pseudo:
            pseudo = self.pseudo_terms_for(persona)
            if pseudo:
                cursor = self.pseudo_cursor.get(persona.id, 0)
                items.append((pseudo[cursor % len(pseudo)], "pseudo"))
                self.pseudo_cursor[persona.id] = cursor + 1

        for term, _ in items:
            probed.add(term)
        return items

    # --- one session -------------------------------------------------------

    def run_session(
        self,
        *,
        persona: Any,
        memory: MemoryModel,
        round_index: int,
        session_start: datetime,
        now: datetime,
        this_session_terms: tuple[str, ...],
        story: str,
        glosses: dict[str, str],
    ) -> ProbeSession:
        n = self.sessions_run.get(persona.id, 0)
        self.sessions_run[persona.id] = n + 1
        include_pseudo = (n % PSEUDO_EVERY_N_SESSIONS) == 0

        selected = self.select_items(
            persona=persona,
            memory=memory,
            this_session_terms=this_session_terms,
            session_start=session_start,
            now=now,
            round_index=round_index,
            include_pseudo=include_pseudo,
        )
        rng = random.Random(f"{persona.seed}:{persona.id}:probe-voice:{round_index}")

        items: list[ProbeItem] = []
        for term, kind in selected:
            is_pseudo = kind == "pseudo"
            if is_pseudo:
                sampled = 0
                r_at, p_def = 0.0, 0.0
                days = None
            else:
                sampled = memory.sample_rung(term, now)
                r_at, p_def, _ = memory.ladder(term, now)
                days = memory.days_since_exposure(term, now)

            if self.live:
                graded, confab, answer, reason = self._live_item(
                    persona=persona,
                    term=term,
                    is_pseudo=is_pseudo,
                    rung=sampled,
                    story=story,
                    gloss=glosses.get(term, ""),
                    rng=rng,
                )
            else:
                graded, confab, answer, reason = self._stub_item(
                    persona_id=persona.id, is_pseudo=is_pseudo, rung=sampled
                )

            items.append(
                ProbeItem(
                    term=term,
                    is_pseudo=is_pseudo,
                    kind=kind,
                    sampled_rung=sampled,
                    graded_rung=graded,
                    confabulated=confab,
                    days_since_last_exposure=None if days is None else round(days, 4),
                    r_at_probe=round(r_at, 4),
                    p_define_at_probe=round(p_def, 4),
                    answer=answer,
                    grader_reason=reason,
                )
            )

            # Reactivity (§0.4): the probe is a retrieval event and is modelled
            # as one. Pseudo-terms are not in the model and get no update.
            if not is_pseudo:
                context_id = f"probe:{round_index}:{term}"
                if graded >= SUCCESS_RUNG:
                    memory.retrieval_success(
                        term, now, new_context=memory.new_context(term, context_id), feedback=True
                    )
                else:
                    memory.retrieval_failure(term, now, feedback=True)

        return ProbeSession(round_index=round_index, at=now.isoformat(), items=tuple(items))

    # --- offline stub --------------------------------------------------------

    def _stub_item(
        self, *, persona_id: str, is_pseudo: bool, rung: int
    ) -> tuple[int, bool, str, str]:
        """The offline persona answers at exactly the sampled rung; the stub
        grader returns it. Every Nth pseudo-term probe confabulates so the flag
        path is exercised."""
        if is_pseudo:
            k = self.pseudo_count.get(persona_id, 0) + 1
            self.pseudo_count[persona_id] = k
            if k % STUB_CONFABULATE_EVERY == 0:
                return 0, True, "", "stub: confident definition of a pseudo-term"
            return 0, False, "", "stub: never seen"
        return rung, False, "", f"stub: answered at rung {rung}"

    # --- live --------------------------------------------------------------

    def _text(self, response: Any) -> str:
        return "".join(
            block.text
            for block in response.content
            if getattr(block, "type", "") == "text"
        ).strip()

    def _note_usage(self, role: str, response: Any) -> None:
        bucket = self.usage.setdefault(role, {"calls": 0, "input_tokens": 0, "output_tokens": 0})
        bucket["calls"] += 1
        usage = getattr(response, "usage", None)
        bucket["input_tokens"] += int(getattr(usage, "input_tokens", 0) or 0)
        bucket["output_tokens"] += int(getattr(usage, "output_tokens", 0) or 0)

    def _live_item(
        self,
        *,
        persona: Any,
        term: str,
        is_pseudo: bool,
        rung: int,
        story: str,
        gloss: str,
        rng: random.Random,
    ) -> tuple[int, bool, str, str]:
        rule_key = rung
        if rung == 0 and is_pseudo and rng.random() < CONFABULATION_RATE:
            rule_key = -1
        style = persona.style
        system = PERSONA_PROBE_SYSTEM.format(
            display_name=persona.display_name,
            profile=persona.profile.get("bio", ""),
            rung_rule=_RUNG_RULES[rule_key],
            case_rule=(
                "Write entirely in lowercase."
                if style.lowercase
                else "Capitalise and punctuate normally."
            ),
        )
        # The canonical gloss and the story reach the persona only at rungs
        # >= 2; below that it must answer from what it (does not) remember.
        if rung >= 2 and gloss:
            knowledge = f"What it means (in your own words when you answer): {gloss}"
        else:
            knowledge = ""
        user = PERSONA_PROBE_USER.format(term=term, knowledge=knowledge, story=story)
        response = self.client.messages.create(
            model=self.persona_model,
            max_tokens=self.max_tokens,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
        self._note_usage("probe_persona", response)
        answer = self._text(response)
        self.transcript.append(
            {"persona": persona.id, "term": term, "role": "persona", "text": answer}
        )

        gloss_line = (
            "This is a PSEUDO-TERM: it does not exist in the domain. Any confident "
            "definition is confabulation."
            if is_pseudo
            else f"Canonical gloss: {gloss or '(the term as used in the story)'}"
        )
        grade = self.client.messages.create(
            model=self.grader_model,
            max_tokens=300,
            system=GRADER_SYSTEM,
            messages=[
                {
                    "role": "user",
                    "content": GRADER_USER.format(
                        term=term, gloss_line=gloss_line, story=story, answer=answer
                    ),
                }
            ],
        )
        self._note_usage("probe_grader", grade)
        verdict_text = self._text(grade)
        self.transcript.append(
            {"persona": persona.id, "term": term, "role": "grader", "text": verdict_text}
        )
        graded, confab, reason = _parse_grade(verdict_text)
        return graded, confab, answer, reason


def _parse_grade(text: str) -> tuple[int, bool, str]:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return 0, False, f"unparseable grade: {text[:80]!r}"
    try:
        data = json.loads(match.group(0))
    except json.JSONDecodeError:
        return 0, False, f"unparseable grade: {text[:80]!r}"
    try:
        rung = int(data.get("rung", 0))
    except (TypeError, ValueError):
        rung = 0
    rung = max(0, min(3, rung))
    return rung, bool(data.get("confabulated", False)), str(data.get("reason", ""))


def gloss_for(term: str, texts: list[str]) -> str:
    """The sentence in the system's own prose that carries `term` -- the
    closest thing to a canonical gloss the harness has, taken from what the
    system actually showed the persona rather than from a hidden glossary."""
    from .responders import term_pattern

    pattern = term_pattern(term)
    for text in reversed(texts):
        for sentence in re.split(r"(?<=[.?!)])\s+", text or ""):
            if pattern.search(sentence):
                return sentence.strip()[:400]
    return ""
